### ISSUE TITLE
Cache Management 2.0.18

### ISSUE THREAD

**Issue by vendeesign** [wpquads/quick-adsense-reloaded#292]
Hello,

In continuation with the issue #262 and #265

I just tested with the 2.0.18 and WP QUADS PRO 2.0.2 (WP Rocket) and there's still a problem.

When you do the test, you have to make it in private browsing. If you're connected, you can't see the problem, as the cache is disabled by default for connected users.

**We have to test both ways, mobile and desktop.** When you load the page on desktop first, it doesn't work. And when you load the page on mobile first, it's ok. 

The test process should be : (Mobile) 👍 

Creating a new ad, with an interdiction to display it on Desktop
Emptying the caches
Loading a website page on your mobile (disconnected of wordpress) --> the ad loads correctly
Loading the same page in private on your Desktop (disconnected of wordpress) -> The ad is not loading. **Is correct.**

The test process should be : (Desktop) 👎 

Creating a new ad, with an interdiction to display it on Desktop
Emptying the caches
Loading a website page on your Desktop (disconnected of wordpress) --> The ad is not loading. 
Loading the same page in private on your Mobile (disconnected of wordpress) -> The ad is not loading.  **Not correct.**

Thanks

Benjamin

**Comment by jasthilokesh** [comment]
Hi There,

We have checked it and we found the issue is from the wp-cache plugin as when the site is open on mobile the site is serving from the mobile cache file and when the site is open on the desktop it is getting serving from the desktop cache file but when the site is moving from the desktop to mobile view then the mobile cache file is not creating, instead desktop file is getting serve due to this the issue is occurring. The problem is with the wp-cache plugin. Technical there is no problem from our end.

Please see this video the issue is clearly shown in it: https://monosnap.com/file/PnFs3VPnx86SiO2lsdinFalP7h1J73

If you have any queries please let me know.

Thank you.
