### ISSUE TITLE
Some Queries running in post section, post edit section and on front end

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [wpquads/quick-adsense-reloaded#841]
Some Queries running in the post section, post edit section, and on the front end, are not required in that section.
https://prnt.sc/xUkDS0_tOJN6
https://prnt.sc/wqB2YpXZT0ZD

**Comment by akshaywali** [comment]
![image](https://github.com/wpquads/quick-adsense-reloaded/assets/36995680/60857379-71cf-41dc-966a-f523e6b3053f)

**1) These are IMP DB query to check tables exists . These queries will run only when admin is logged in, so any other user or visitior would not trigger these query . Also time take by these query is 0.0007-0.0010 sec so they don't impact server.**  

![image](https://github.com/wpquads/quick-adsense-reloaded/assets/36995680/2c1caa64-c2d9-49c9-bce7-3d3fa81fdaf0)

**2) This query is required in the logic to get ads on current page . So this is also required query also this query   take arounf 0.0002-0.0005 sec to execute so there is not much impact .**


**_NOTE :- However if the server is already slow due to traffic or other plugins or limited resources. Then these query may take more time to execute_**
